### ISSUE TITLE
HashCorp Vault setup issue in Existing EKS Cluster

### ISSUE THREAD

**Issue by karthiDS15** [aws-quickstart/quickstart-eks-hashicorp-vault#40]
Hi,
While we try to setup Vault using the quick start guide. Facing few issues in setup.

VaultNameSpace	CREATE_FAILED	Resource handler returned message: "" (RequestToken: 98251d73-8ccb-58d7-2e3b-a3191e69441d, HandlerErrorCode: InternalFailure)
ManagedNodeGroup	CREATE_FAILED	Nodegroup Vault-sg failed to stabilize: [{Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds:

`Exception caught error: You must be logged in to the server (the server has asked for the client to provide credentials)
Traceback (most recent call last):
  File "/var/task/awsqs_kubernetes_resource/utils.py", line 67, in run_command
    shlex.split(command), stderr=subprocess.STDOUT
  File "/var/lang/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/var/lang/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', 'create', '--save-config', '-o', 'yaml', '-f', '/tmp/manifest.yaml', '-n', 'default']' returned non-zero exit status 1.
`

**Reference link -** https://aws-quickstart.github.io/quickstart-eks-hashicorp-vault/
**Deployment option -** Deploy into an existing Amazon EKS cluster (https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/create/template?templateURL=https%3A%2F%2Faws-quickstart.s3.us-east-1.amazonaws.com%2Fquickstart-amazon-eks%2Fsubmodules%2Fquickstart-eks-hashicorp-vault%2Ftemplates%2Fquickstart-eks-hashicorp-vault.template.yml)

**Prerequisite setup is done following this link** 
https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/create/template?stackName=Amazon-EKS&templateURL=https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-amazon-eks/templates/amazon-eks-entrypoint-existing-cluster.template.yaml

Once the prerequisite is done, EKSAdminRoleArn and HelmRoleArn are updated in aws-auth config map.

Can you check this issue please?

Thanks

**Comment by karthiDS15** [comment]
Issue was with the VPC endpoint (EC2 interface) where the instances were not able to join the cluster. Post updating the security group of the VPC endpoint, this issue is not seen any more.
